#!/usr/bin/python
import cgitb
cgitb.enable()

print "Content-type: text/html\n"

print """
<html>

<head>
  <title>Prog 282 Basics</title>
  <meta name='viewport' content='width=device-width,minimum-scale=1.0,maximum-scale=1.0' />
</head>

<body>

  <h3>Python Script</h3>
  <p>This file generated by a simple Python script.

</body>
</html>
"""